### ISSUE TITLE
should be SAPCP_test

### ISSUE THREAD

**Issue by wombling** [grahamrobbo/scp_test#1]
![image](https://user-images.githubusercontent.com/2967008/32601609-4f374a66-c597-11e7-8695-af458b516676.png)

also seems your repo allows public to raise issues 😁

**Comment by grahamrobbo** [comment]
![image](https://user-images.githubusercontent.com/1305633/33003201-477d17a0-ce0d-11e7-810b-c28d261ec35d.png)
